#!/usr/bin/env python3
"""
build_hoods.py -- T-040 step B2 (`hood-dataset/TRD.md` section 4.5).

One authored source, one generator run, two generated artifacts, no
database access required (TRD section 2.1):

    database/data/hoods-tel-aviv.source.json
                     |
                     v
              build_hoods.py -- validate (validate_dataset.py) --> fail
                     |            loudly, write nothing, on any violation
        +------------+------------+
        v                         v
  migrations/NNN_hoods_    passenger-code/.../Resources/
  tel_aviv_data.sql          hoods-tel-aviv.json
     (DB seed)                  (iOS bundle)

Usage:
    python3 build_hoods.py --migration-number NNN [--check]
        [--source database/data/hoods-tel-aviv.source.json]
        [--sql-out database/migrations/NNN_hoods_tel_aviv_data.sql]
        [--json-out ../../../passenger-code/Passenger/Resources/hoods-tel-aviv.json]

--check validates only, writes nothing, exits non-zero on any violation
(error-level; warnings print but do not fail --check).

No network, no DATABASE_URL, no credentials (TRD section 4.5). Deterministic:
same source in, byte-identical artifacts out -- hoods sorted by id, stable
float formatting -- so a reviewer can regenerate and `git diff --exit-code`
to prove the committed artifacts match the committed source.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from validate_dataset import (  # noqa: E402
    load_hood_source,
    validate_hoods,
    slug_preservation_warning,
    PREVIOUSLY_SEEDED_SLUGS,
    area_centroid,
)

BUNDLE_SCHEMA_VERSION = 2
DEFAULT_SOURCE = Path(__file__).resolve().parent.parent / "data" / "hoods-tel-aviv.source.json"
DEFAULT_JSON_OUT = (
    Path(__file__).resolve().parents[3]
    / "passenger-code" / "Passenger" / "Resources" / "hoods-tel-aviv.json"
)
DEFAULT_MIGRATIONS_DIR = Path(__file__).resolve().parent.parent / "migrations"

ATTRIBUTION_NOTICE = (
    "Hood boundary geometry in this dataset (see database/data/hoods-tel-aviv.source.json, "
    "per-row `provenance.source`) is derived in part from OpenStreetMap data, "
    "(c) OpenStreetMap contributors, available under the Open Database License (ODbL) 1.0 "
    "-- https://www.openstreetmap.org/copyright . Rows with provenance.source == 'manual' "
    "are hand-authored referencing real neighbourhood shapes/names, not an authoritative "
    "municipal or OSM source -- see the row's own provenance.sourceRef for what that means "
    "case by case. ODbL's attribution and share-alike-on-derived-databases obligations "
    "apply to the osm-sourced rows. Whether attribution must additionally be *displayed "
    "in-app* is not decided by this script -- it is Aviran's call (PAS-6 item 15; "
    "hood-dataset TRD sec 8 D8)."
)


def _fmt_float(x: float) -> str:
    """Stable float formatting: up to 6dp, no trailing zeros, no exponent."""
    s = f"{x:.6f}".rstrip("0").rstrip(".")
    return s if s else "0"


def build_bundle(dataset, source_digest: str) -> dict:
    hoods = []
    for hood in sorted(dataset.hoods, key=lambda h: h.id):
        centroid = area_centroid(hood.polygon)
        hoods.append(
            {
                "id": hood.id,
                "name": hood.name,
                "polygon": hood.polygon,
                "centroid": [centroid[0], centroid[1]],
                "blurb": hood.blurb,
                "isTouristTrap": hood.is_tourist_trap,
                "designatedForProgression": hood.designated_for_progression,
            }
        )
    return {
        "schemaVersion": BUNDLE_SCHEMA_VERSION,
        "generatedAt": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "city": dataset.city,
        "_attribution": ATTRIBUTION_NOTICE,
        "hoods": hoods,
    }


def _sql_literal_text(value) -> str:
    if value is None:
        return "null"
    escaped = value.replace("'", "''")
    return f"'{escaped}'"


def _sql_literal_bool(value) -> str:
    if value is None:
        return "null"
    return "true" if value else "false"


def _sql_literal_polygon(ring) -> str:
    pts = ",".join(f"[{_fmt_float(lng)},{_fmt_float(lat)}]" for lng, lat in ring)
    return f"'[{pts}]'::jsonb"


def build_migration_sql(dataset, migration_number: str, source_digest: str) -> str:
    sorted_hoods = sorted(dataset.hoods, key=lambda h: h.id)
    lines = []
    lines.append(f"-- {migration_number}_hoods_tel_aviv_data.sql")
    lines.append("-- GENERATED by database/scripts/build_hoods.py from database/data/hoods-tel-aviv.source.json")
    lines.append("-- Do not hand-edit. Re-run the generator instead (hood-dataset/TRD.md sec 3.3).")
    lines.append(f"-- Source digest: sha256:{source_digest}")
    lines.append("--")
    lines.append("-- Task: T-040 (hood-dataset). Requires 003_hood_attributes.sql to have run first")
    lines.append("-- (adds blurb / is_tourist_trap / designated_for_progression to public.hoods).")
    lines.append("--")
    lines.append("-- Attribution (hood-dataset/TRD.md sec 8 D8; see database/data/hoods-tel-aviv.source.json")
    lines.append("-- for the full notice and per-row provenance):")
    for line in ATTRIBUTION_NOTICE.split(". "):
        line = line.strip().rstrip(".")
        if line:
            lines.append(f"--   {line}.")
    lines.append("--")
    lines.append(
        "-- Upsert, not `on conflict do nothing`: 001's placeholder rows must not survive"
    )
    lines.append(
        "-- under a shared id (hood-dataset/TRD.md sec 3.3 / sec 8 D4). The delete below is"
    )
    lines.append(
        "-- scoped to city = 'tel-aviv' and prunes any placeholder id the real dataset drops."
    )
    lines.append("")
    lines.append("insert into public.hoods (id, name, city, polygon, blurb, is_tourist_trap, designated_for_progression) values")
    value_lines = []
    for hood in sorted_hoods:
        value_lines.append(
            "  ("
            + ", ".join(
                [
                    _sql_literal_text(hood.id),
                    _sql_literal_text(hood.name),
                    _sql_literal_text(dataset.city),
                    _sql_literal_polygon(hood.polygon),
                    _sql_literal_text(hood.blurb),
                    _sql_literal_bool(hood.is_tourist_trap),
                    _sql_literal_bool(hood.designated_for_progression),
                ]
            )
            + ")"
        )
    lines.append(",\n".join(value_lines) + "")
    lines.append("on conflict (id) do update set")
    lines.append("  name                       = excluded.name,")
    lines.append("  polygon                    = excluded.polygon,")
    lines.append("  blurb                      = excluded.blurb,")
    lines.append("  is_tourist_trap            = excluded.is_tourist_trap,")
    lines.append("  designated_for_progression = excluded.designated_for_progression,")
    lines.append("  updated_at                 = now();")
    lines.append("")
    id_array = ", ".join(_sql_literal_text(h.id) for h in sorted_hoods)
    lines.append("delete from public.hoods")
    lines.append(f" where city = {_sql_literal_text(dataset.city)}")
    lines.append(f"   and id <> all (array[{id_array}]);")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--sql-out", type=Path, default=None)
    parser.add_argument("--json-out", type=Path, default=DEFAULT_JSON_OUT)
    parser.add_argument("--migration-number", default=None, help="e.g. 006 -> 006_hoods_tel_aviv_data.sql")
    parser.add_argument("--check", action="store_true", help="Validate only; write nothing; non-zero exit on any error-level violation")
    args = parser.parse_args()

    if not args.check and not args.migration_number:
        parser.error("--migration-number is required unless --check is passed")

    source_bytes = args.source.read_bytes()
    source_digest = hashlib.sha256(source_bytes).hexdigest()

    dataset = load_hood_source(args.source)
    violations = validate_hoods(dataset)
    warnings_slug = slug_preservation_warning(dataset, PREVIOUSLY_SEEDED_SLUGS)

    errors = [v for v in violations if v.level == "error"]
    warns = [v for v in violations if v.level == "warning"] + warnings_slug

    for v in violations + warnings_slug:
        print(v, file=sys.stderr)

    if errors:
        print(f"\n{len(errors)} error(s), {len(warns)} warning(s), {len(dataset.hoods)} hoods -- WRITING NOTHING", file=sys.stderr)
        return 1

    print(f"{len(errors)} error(s), {len(warns)} warning(s), {len(dataset.hoods)} hoods -- clean", file=sys.stderr)

    if args.check:
        return 0

    sql_out = args.sql_out or (DEFAULT_MIGRATIONS_DIR / f"{args.migration_number}_hoods_tel_aviv_data.sql")

    bundle = build_bundle(dataset, source_digest)
    sql_text = build_migration_sql(dataset, args.migration_number, source_digest)

    args.json_out.parent.mkdir(parents=True, exist_ok=True)
    with open(args.json_out, "w", encoding="utf-8") as f:
        json.dump(bundle, f, indent=2, ensure_ascii=False)
        f.write("\n")

    sql_out.parent.mkdir(parents=True, exist_ok=True)
    with open(sql_out, "w", encoding="utf-8") as f:
        f.write(sql_text)

    print(f"Wrote {len(bundle['hoods'])} hoods to {args.json_out}", file=sys.stderr)
    print(f"Wrote {sql_out}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
